//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPhotoImmobilier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agence
    {
        public Agence()
        {
            this.Agents = new HashSet<Agent>();
        }
    
        public int AgenceId { get; set; }
        public string Nom { get; set; }
        public string Adresse { get; set; }
        public string NumTel { get; set; }
    
        public virtual ICollection<Agent> Agents { get; set; }
    }
}
