//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPhotoImmobilier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forfait
    {
        public Forfait()
        {
            this.Seances = new HashSet<Seance>();
        }
    
        public int ForfaitId { get; set; }
        public string Nom { get; set; }
        public string DescriptionForfait { get; set; }
        public string Prix { get; set; }
    
        public virtual ICollection<Seance> Seances { get; set; }
    }
}
