//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPhotoImmobilier.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(RdvMetaData))]
    public partial class Rdv
    {
        public int RdvId { get; set; }
        public Nullable<bool> Confirmer { get; set; }
        public string Client { get; set; }
        public string Photographe { get; set; }
    
        public virtual Seance Seance { get; set; }
    }
}
